name: build

on:
  push:
    branches: [main, deepmind]
  pull_request:
    branches: [main]

jobs:
  mujoco_mpc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            additional_label: "with Clang 14"
            cmake_args: >-
              -G Ninja
              -DCMAKE_C_COMPILER:STRING=clang-14
              -DCMAKE_CXX_COMPILER:STRING=clang++-14
              -DMJPC_BUILD_GRPC_SERVICE:BOOL=ON
            additional_targets: "agent_server"
            tmpdir: "/tmp"
          - os: macos-12
            cmake_args: >-
              -G Ninja
              -DMJPC_BUILD_GRPC_SERVICE:BOOL=ON
            additional_targets: "agent_server"
            tmpdir: "/tmp"
          - os: windows-2022
            cmake_args: >-
              -G Ninja
              -DCMAKE_C_COMPILER:STRING=clang
              -DCMAKE_CXX_COMPILER:STRING=clang++
              -DMJPC_BUILD_GRPC_SERVICE:BOOL=ON
            tmpdir: "C:/Temp"

    name: "MuJoCo MPC on ${{ matrix.os }} ${{ matrix.additional_label }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Linux
      if: ${{ runner.os == 'Linux' }}
      run: >
        sudo apt-get update && sudo apt-get install
        libgl1-mesa-dev
        libxinerama-dev
        libxcursor-dev
        libxrandr-dev
        libxi-dev
        ninja-build
    - name: Prepare macOS
      if: ${{ runner.os == 'macOS' }}
      run: brew install ninja
    - name: Prepare Windows
      if: ${{ runner.os == 'Windows' }}
      run: choco install nasm
    - name: Configure MuJoCo MPC
      run: >
        mkdir build &&
        cd build &&
        cmake .. -DCMAKE_BUILD_TYPE:STRING=Release
        ${{ matrix.cmake_args }}
    - name: Build MuJoCo MPC
      working-directory: build
      run: cmake --build . --config=Release ${{ matrix.cmake_build_args }} --target mjpc agent_test cost_derivatives_test norm_test rollout_test threadpool_test trajectory_test utilities_test estimator_force_test estimator_optimize_test estimator_prior_test estimator_sensor_test estimator_shift_test estimator_trajectory_test estimator_utilities_test ${{ matrix.additional_targets }}
    - name: Test MuJoCo MPC
      working-directory: build
      run: ctest -C Release --output-on-failure .
      